sudo apt remove falkon
sleep 5 && clear
sudo apt remove sqlitebrowser
sleep 5 && clear
sudo apt remove docker.io
sleep 5 && clear
sudo apt remove tk
sleep 5 && clear
sudo apt remove python3-tk
sleep 5 && clear
sudo apt remove python3-pip
sleep 5 && clear
sudo apt remove frozen-bubble
sleep 5 && clear
sudo apt remove pingus
sleep 5 && clear
sudo apt remove steam
sleep 5 && clear
sudo apt remove cmatrix
sleep 5 && clear
sudo apt remove tree
sleep 5 && clear
sudo apt remove psensor
sleep 5 && clear
sudo apt remove vnstat
sleep 5 && clear
sudo apt remove conky-all
sleep 5 && clear
sudo apt remove kleopatra
sleep 5 && clear
sudo apt remove virtualbox-guest-additions-iso
sleep 5 && clear
sudo apt remove virtualbox-ext-pack
sleep 5 && clear
sudo apt remove virtualbox
sleep 5 && clear
sudo apt remove krita
sleep 5 && clear
sudo apt remove scribus-template
sleep 5 && clear
sudo apt remove scribus
sleep 5 && clear
sudo apt remove guvcview
sleep 5 && clear
sudo apt remove cheese
sleep 5 && clear
sudo apt remove handbrake
sleep 5 && clear
sudo apt remove okular
sleep 5 && clear
sudo apt remove pdfarranger
sleep 5 && clear
sudo apt remove gftp
sleep 5 && clear
sudo apt remove keepass2
sleep 5 && clear
sudo apt remove notepadqq
sleep 5 && clear
sudo apt remove remmina
sleep 5 && clear
sudo apt remove gtkhash
