#!/usr/bin/env bash

# Import Current Theme
DIR="$HOME/.config/rofi/"
STYLE="default"
RASI="$DIR/rasi/askpass.rasi"

# rofi text dialog to get password
rofi -dmenu \
     -password \
     -i \
     -p "Root" \
     -theme ${RASI}
